autoInstallPeers: false
enablePrePostScripts: true
ignoreWorkspaceRootCheck: true
shamefullyHoist: true
shellEmulator: true
strictPeerDependencies: false
trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 43200

overrides:
  vue-demi: latest

onlyBuiltDependencies:
  - esbuild
  - vue-demi
