ignoreWorkspaceRootCheck: true
shamefullyHoist: true
shellEmulator: true
trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 43200
strictPeerDependencies: false
autoInstallPeers: false
enablePrePostScripts: true

onlyBuiltDependencies:
  - esbuild
  - vue-demi
